# Generated by Django 2.2.2 on 2019-06-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.DecimalField(decimal_places=4, max_digits=10)),
                ('times_read', models.IntegerField()),
                ('published_on', models.DateTimeField(auto_now=True)),
                ('readkey', models.TextField()),
            ],
        ),
    ]
